Feature/el e1
alvarez98/e-learning-system pull request #26
Opened 2020-08-08 01:50 UTC by paulspartan14

2020-08-08 16:17 UTC, Alvarez-P requested changes
Debes poner una descripcion de tu PR, asi como mencionar la issue que resuelves

2020-08-08 16:17 UTC, alvarez98 commented on src/controllers/enrollments.js
> + *
quita estos espacios

2020-08-09 02:57 UTC, paulspartan14 commented on src/controllers/enrollments.js
> + *
listo, mi pr resuelve la ruta de enrollments que se encarga de las inscripciones en la ruta /api/enrollments

2020-08-09 02:59 UTC, Alvarez-P approved these changes

2020-08-09 03:00 UTC, merged