Feature/EL-U4 #29
alvarez98/e-learning-system pull request #33
Opened 2020-08-20 20:05 UTC by Victoriasaurio

Función agregada en el controlador que permite obtener un usuario por medio de su id. Se debe estar logueado(admin o el propio usuario) para poder obtener una respuesta.

2020-08-20 20:33 UTC, alvarez98 commented on src/schemas/userSchema.js
> +    }),
debes validar que sea un uuid correcto, ahi bien podria mandar cualquier palabra

2020-08-20 20:36 UTC, Alvarez-P requested changes

2020-08-20 20:36 UTC, alvarez98 commented on src/schemas/userSchema.js
> +
debes validar que sea un uuid correcto, ahi bien podria mandar cualquier palabra

2020-08-22 02:08 UTC, Alvarez-P approved these changes

2020-08-22 02:10 UTC, merged